[workspace]
channels = ["conda-forge"]
name = "miapbp-pixi-demo"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.5,<3.14"
jax = ">=0.7.0,<0.8"

[feature.gpu.system-requirements]
cuda = "12.4"

[feature.gpu.target.linux-64.dependencies]
jax = ">=0.7.0,<0.8"
pytorch-gpu = ">=2.7.1,<3"
cuda-version = "==12.6"
python = ">=3.13.5,<3.14"

[environments]
gpu = ["gpu"]
