[workspace]
channels = ["conda-forge"]
name = "miapbp-pixi-demo"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.5,<3.14"

[feature.cpu.dependencies]
jax = ">=0.7.0,<0.8"
pytorch = ">=2.7.1,<3"
torchvision = ">=0.22.0,<0.23"

[feature.cpu.tasks.train-cpu]
description = "Train a PyTorch CNN on MNIST on CPU as a local test"
args = [ { "arg" = "epochs", "default" = "--epochs 2" } ]
cmd = "time python ./app/torch_MNIST.py {{ epochs }}"

[feature.gpu.system-requirements]
cuda = "12.4"

[feature.gpu.target.linux-64.dependencies]
python = ">=3.13.7,<3.14"
pytorch-gpu = ">=2.7.1,<3"
torchvision = ">=0.22.0,<0.23"
jax = ">=0.7.0,<0.8"
cuda-version = "12.9.*"

[feature.gpu.tasks.check]
description = "Check if GPU is visible to PyTorch"
cmd = "python ./app/torch_detect_GPU.py"

[feature.gpu.tasks.train]
description = "Train a PyTorch CNN on MNIST on GPU"
args = [ { "arg" = "epochs", "default" = "--epochs 14" } ]
cmd = "time python ./app/torch_MNIST.py {{ epochs }} --save-model"

[feature.lab.dependencies]
notebook = ">=7.4.5,<8"
jupyterlab = ">=4.4.6,<5"

[feature.lab.tasks.start]
description = "Launch Jupyter Lab"
cmd = "jupyter lab"

[environments]
cpu = ["cpu"]
gpu = ["gpu"]
lab-cpu = ["cpu", "lab"]
lab-gpu = ["gpu", "lab"]
